### ISSUE TITLE
select drop down not able to close in Modal Dialog

### ISSUE THREAD

**Issue by shaikimran8733** [basvandenberg/angular2-select#86] opened 2017-01-30 19:33 UTC
I have a select menu that appears in a modal,on selecting dropdown  value or on clicking in entire modal the dropdown is not able to close.
#In select component ,window events for closing select not working in dialog

**Comment by basvandenberg** [comment] 2017-01-31 20:28
To me this sounds like a bug in the modal, preventing the click event to bubble up to the 'window level'. The select menu closes when it captures a window click event (outside of the menu). If the modal stops propagation of this event, the menu will not close.

If you think it's a bug in the select menu, please provide a plunker to show this issue.

**Comment by basvandenberg** [comment] 2017-02-11 10:39
Closing this issue for now. If the issue is still not solved, and the cause of the issue is in this select component, then please let me know. Then I'll reopen the issue.

**Closed by basvandenberg** 2017-02-11 10:39 UTC
