### ISSUE TITLE
Control [options] does not respect myModel?.MyAttrib throwing "Cannot read property 'length' of null"

### ISSUE THREAD

**Issue by mulgurul** [basvandenberg/angular2-select#56] opened 2016-12-12 15:23 UTC
I'm loading all option values async, so controls needs to wait with binding.

This works for all standard controls, using model**?**.age or what ever.

But it seems that the angular2-select does not respect this but needs a defined model by default making it impossible to load model async.

Can this be fixed or is there a workaround/option to deal with this?

Best regards, Peter Meldgaard

**Comment by brandonreid** [comment] 2017-01-03 21:55
@mulgurul I usually fix this by setting something like  `*ngIf="optionsLoaded"` so the select menu doesn't build until the options show up.

**Comment by cmkramer** [comment] 2017-01-26 14:33
True, I have the same issue and the same "solution". It would be nicest if the select either used the same method as the material2 appraoch (i.e. passing a list of options in the HTML using a repeat instead of passing them as an attribute property), or if the supplied list could be an observable.

**Comment by basvandenberg** [comment] 2017-01-31 21:25
@cmkramer Could you please provide some code to illustrate your issue? I am not sure if I correctly understand you. I thought that @mulgurul 's issue would have been solved in the beta release, but apperantly this is not the case.

I would say that passing the options as HTML repeat only makes sense if you want your options to be customizable HTML (for example adding an icons to your options). For this component only strings are required (customized HTML options are not supported). So with a HTML repeat, you would need to have a list with strings that you provide to the HTML repeat, so why not immediately provide these strings to the select component?

The supplied list is not an observable, but changes are detected (by angular). It is detected if the list is being replaced with a new list, not if an existing list is modified, see #60 for more details.

**Comment by basvandenberg** [comment] 2017-02-11 11:59
Closing this issue for now.

**Closed by basvandenberg** 2017-02-11 11:59 UTC

**Comment by cmkramer** [comment] 2017-02-11 19:13
Well it seems that with your current version it no longer crashes when the form control aready has a value, but the list isn't loaded yet, which is nice. Still, when the forrmcontrol already has a value set, while retrieving the option list asynchronously, the option is not properly selected after the list is loaded. You can see this effect here:

https://plnkr.co/edit/jdFI1xprLKp1tX9lTsAX?p=preview

This still forces the user to explicitly delay adding the select component to the page until after the option list has been loaded, to avoid its value not being displayed properly.

**Comment by cmkramer** [comment] 2017-02-12 14:10
@basvandenberg would you like me to create a new issue for this?

**Comment by basvandenberg** [comment] 2017-02-12 15:08
I am not sure if this is an issue. If I understand you correct, you try to set a value of an option that is not there (because the options are not yet loaded). In my opinion, the expected behavior is that no option is selected in that case, which is what currently happens. 

Instead of letting the component 'remember' what value was set, and then setting it as soon as options are set (this could lead to confusing situation and is in my opinion not very intuitive), the user should set the value after he has set the options. So for example: 

- Add the control with an empty list of options, and _without_ setting a value.
- At the same, start asynchronous loading of the options (which returns an observable).
- Subscribe to the observable and when the data is loaded:
    - Replace the empy list of options with the loaded options.
    - _Now_ set the control's value.

I adjusted your plunker a bit to illustrate this:

https://plnkr.co/edit/K2F2cCXbJajUijSIYIc6?p=preview

```
setTimeout(() => {
    this.options0 = opts.slice(0);
    this.singleSelectDisabled = false;
    setTimeout(() => { this.form.controls['selectSingle'].setValue('0'); });
}, 2000);
```

Additionally I disabled the select component as long as the options are not set. After two seconds the options are set and the component is enabled.

And _then_ set the value.

**However**, as you can see this is done within a [zero delay `setTimeout`]((https://developer.mozilla.org/en/docs/Web/JavaScript/EventLoop#Zero_delays)). This looks strange and I guess it is a bit of a hack, but you'll see it quit often in angular2 apps. This is to make sure that angular's change detection detected the updated list of options before setting the value. It won't work without the zero delay `setTimeout`.

 (by using a zero-delay `setTimeout`, the `setValue` task is pushed to the end of the task queue, guarantied to be behind the task that handles the change detection)

**Comment by cmkramer** [comment] 2017-02-12 17:27
Thank you for thinking along. I am indeed aware of how a setTimeout can force something out of the current digest cycle and push it into the next. I'm glad you also realize this is a hack. Seeing it often doesn't make it right, so I'd rather use it less often than more often.

I'd like to picture this case as follows:

I have a persisted record, that I serve through a restful resource. My Angular application has access to this record and has a corresponding reactive form that allows me to edit the record. Since the record is served through a singleton ResourceStore, Collection or whichever name fits (comparable to ReactJS's Redux), there's always one truth, both when it comes to the record, and its corresponding form. This also means that the form itself, in it's initial state, is loaded when the record is loaded. So at that point control values are set to the currently persistent values as known by the server.

Now all the component has to do is present the user with an interface that allows them to edit the current state of the resource. In my perspective it makes sense that any component used to represent a form item, should take care of synchronizing its own resources. In this case it takes more than one resource to work, i.e. the control value and the option list. So which of the two is initialized first, or second should not stop the component from providing the one thing that it is created for. It doesn't sound right the programmer using the form editing component has to build logic into every encapsulating component in order for it to work, while it doesn't add any value to the encapsulating component itself. This means duplicate code everywhere, while it could be taken care of by the form editing component itself.

Either way, shouldn't a component strive behave the same regardles of the sequence or timing in which properties are loaded?

**Comment by basvandenberg** [comment] 2017-02-13 18:16
That's an interesting view, haven't thought about it like that. I do see some practical issues though. But I'll have to come back to you about this later, because I don't have much time now and I will be away for some days.

**Comment by cmkramer** [comment] 2017-02-14 10:51
Awesome, can't wait to see what you'll do :).
