### ISSUE TITLE
multiple select backspace not removing

### ISSUE THREAD

**Issue by GoNode5** [basvandenberg/angular2-select#101] opened 2017-02-09 12:31 UTC
key backspace result in text instead of complete removal last item

![select2](https://cloud.githubusercontent.com/assets/2210672/22783415/f6a3bb66-eecb-11e6-865a-8a03b71b96ff.gif)

**Comment by basvandenberg** [comment] 2017-02-10 11:47
That is the intended behavior, I used the same behavior as that of the [select2](https://select2.github.io/examples.html) JQuery plugin. I would like to stick to that for the moment.

**Comment by GoNode5** [comment] 2017-02-11 00:45
Hope you reconsider. Its UX unfriendly. My users instantly complained, after replacing so I switch back to ng2-selectize. Do like a native solution though, but my users are  always right..

**Comment by basvandenberg** [comment] 2017-02-11 09:58
> Its UX unfriendly

I think that's a matter of taste and what you are used to. As said, for the 1.0 release I will stick to the select2 approach. Thanks for the input, I'll close this issue for now.

**Closed by basvandenberg** 2017-02-11 09:58 UTC
