### ISSUE TITLE
Problem when upgraded new version.

### ISSUE THREAD

**Issue by khoapossible** [basvandenberg/angular2-select#70] opened 2017-01-12 08:46 UTC
I have already upgrade new version, and i got a lot of issues. Angular2-select in new version is very smooth, i loved it. But i got 2 problems.
+ Selected value of new version is array - difference type of old version - so i have to fix all source code. So i got a lot of unexpected problem.
+ Second, this is very important. Angular2-select in new version can not using HTML5 validate (required).

Thank you.

**Comment by basvandenberg** [comment] 2017-01-12 20:00
Thanks for the feedback. A few comments:

1. To make it easier to manage the issues, report each issue separately with a specific title indicating what the issue is.

2. Please check if the issue you are reporting is not already reported and/or fixed. If you search all issues for 'array' you will see that your first issue is the same as issue #66, which is already fixed and released in beta.2.

3. Please note that adding 'Urgent' to the title does not give an issue higher priority or will get it fixed any sooner.

4. If it is important for you to have stable software, don't use pre-release software. And don't upgrade to a just released beta version for which the documentation clearly states:

> Disclaimer: The beta version is a complete rewrite of the alpha version, so new bugs are to be expected. Please do not yet rely on this beta version for production releases.

5. About your second issue. You can use the select component as [form control](https://angular.io/docs/ts/latest/api/forms/index/FormControl-class.html) with the [required](https://angular.io/docs/ts/latest/api/forms/index/Validators-class.html) validator which will keep the form invalid as long as no option is selected.

**Comment by basvandenberg** [comment] 2017-02-11 11:07
First issue was already fixed.
For second issue see #83.

**Closed by basvandenberg** 2017-02-11 11:07 UTC
