### ISSUE TITLE
Wrong labels are shown for select items that do not have a unique value

### ISSUE THREAD

**Issue by RadekTester** [basvandenberg/angular2-select#32] opened 2016-10-30 18:54 UTC
I have a array of 429 elements. Component does not properly interpret value and label. It users value as label instead. I have confirmed that by limiting list to 8 elements. It worked as expected.

**Comment by basvandenberg** [comment] 2016-10-31 07:06
Could you show (part of) your input array? Or a code example? I need more input to investigate what might went wrong here.

**Comment by RadekTester** [comment] 2016-10-31 12:30
Sure. Here you go... 

In my onOnInit I create a formGroup: 

`    ngOnInit(){
       
        this.getAvailableOptions();

        this.form = new FormGroup({});
        this.form.addControl('**timeZoneControl**', new FormControl(''));`

Then I get "options" from http response as follows: 
`getAvailableOptionsReturn( response ){
        this.gettingAvailableOptionsInProgress = false;

        if (response.status == 0){
            var data = response.data;
            
            this.timeZoneOptions = [];
            var i;
            for( i = 0; i < data.timeZoneOptions.length; i++){
                this.**timeZoneOptions**[i] = {value: data.timeZoneOptions[i].value, label: data.timeZoneOptions[i].label  }
            }

            this.currencyOptions = data.currencyOptions;
            //this.timeZoneOptions = data.timeZoneOptions;

            this.getSettingsFromServer();
            return;
        }
    
        this.serverError.handleErrorFromServer( response ); // if we reached this point it means that there was an error;  
     }`

Then my template looks as follows: 

`<ng-select
                                        [options]="timeZoneOptions"
                                        [multiple]="false"
                                        placeholder="{{i18n.get('Please Select')}}"
                                        [allowClear]="false"
                                        (selected)="timeZoneOptionSelected($event)"
                                        formControlName="timeZoneControl"
                                        >
                                    </ng-select>`


I've tested with my PHP code that provides "http" response. Just for referrence: 

`// this ensures that most important time zones are "in front"
		$timeZones = array();
		$timeZones[0]["label"] = "Eastern"; $timeZones[0]["identifier"] = "America/New_York"; $timeZones[0]["value"] = "America/New_York";
		$timeZones[1]["label"] = "Central"; $timeZones[1]["identifier"] = "America/Chicago"; $timeZones[1]["value"] = "America/Chicago"; 
		$timeZones[2]["label"] = "Mountain"; $timeZones[2]["identifier"] = "America/Denver"; $timeZones[2]["value"] = "America/Denver"; 
		$timeZones[3]["label"] = "Mountain no DST"; $timeZones[3]["identifier"] = "America/Phoenix"; $timeZones[3]["value"] = "America/Phoenix"; 
		$timeZones[4]["label"] = "Pacific"; $timeZones[4]["identifier"] = "America/Los_Angeles"; $timeZones[4]["value"] = "America/Los_Angeles"; 
		$timeZones[5]["label"] = "Alaska"; $timeZones[5]["identifier"] = "America/Anchorage"; $timeZones[5]["value"] = "America/Anchorage"; 
		$timeZones[6]["label"] = "Hawaii"; $timeZones[6]["identifier"] = "America/Adak"; $timeZones[6]["value"] = "America/Adak"; 
		$timeZones[7]["label"] = "Hawaii no DST"; $timeZones[7]["identifier"] = "Pacific/Honolulu"; $timeZones[7]["value"] = "Pacific/Honolulu"; 
		$timeZones[8]["label"] = "UTC"; $timeZones[8]["identifier"] = "UTC"; $timeZones[8]["value"] = "UTC"; 
		
		
		$otherIdentifiers = \DateTimeZone::listIdentifiers();
		for( $i = 0; $i < count ( $otherIdentifiers ); $i++){
			$object["label"] = $otherIdentifiers[$i];
			$object["identifier"] = $otherIdentifiers[$i];
			$object["value"] = $otherIdentifiers[$i];
			array_push( $timeZones, $object);
		}
		
		return $timeZones;`

Please let me know if this helps.

Cheers, 
Radek

**Comment by basvandenberg** [comment] 2016-10-31 21:57
Sorry, but this code doesn't give me much insight...

I am not really sure if this is a bug. You say that it works for 8 elements, I see no reason why it shouldn't  work for 429 elements, the component doesn't make a difference between small and large lists.

Please check on the client side (use the chrome development tools to set a breakpoint) to see what is in your `timeZoneOptions` variable. If the the values and labels in that array (the direct input of the select component) do not match the list you see in the select dropdown in your browser, than there might be a bug. 

Before you issue a bug report, please double check that the issue is actually in this component. For example by generating a hardcoded array with your input instead of using a pile of (rather messy) code that gets the list from the server and transforms it, which might just as well contain a bug. Right now it costs me a lot of valuable time while it doesn't contribute to the development of the component.

I'll close this issue for now, I will reopen it if you have hard evidence that the bug is in this component and not in your code.

**Comment by basvandenberg** [comment] 2016-11-01 07:34
My guess is that the bug is in the PHP code. I don't know anything about PHP, but you manually add 9 items to the `$timeZones`, and add the rest in a for loop. That probably explains why it works for the first 9, and not for longer lists, right? Your input is wrong...

Again, I know nothing about PHP, but within the for loop you seem to be storing exactly the same value to the object's `label` and `value`...

**Comment by RadekTester** [comment] 2016-11-01 07:56
Hi. I think infigured it out. Input data is ok as it works fine with
standard html select. And I was double checking that in chrome developer.

What I think is going on is the following
  When you have the same value miltiple times with different labels it
takes last label and apply it to all previous identical values. For example
if data is
Value label
Animal dog
Animal cat
Plant carrot
Plant strawberry

It will show:
Animal cat
Animal cat
Plant strawberry
Plant strawberry

I think  it is somewhere between a bug and feature ;)

I will create some sample code to show it and I will l left you know.

Btw thanks for a nice component I like it a lot.

**Comment by basvandenberg** [comment] 2016-11-01 10:46
There you have a very valid point. I assumed that values would be unique, which of course doesn't have the be the case for a select component. I will have a look at this, it probably needs some refactoring.

**Comment by basvandenberg** [comment] 2017-01-07 12:23
In the beta release the list should show correctly with non-unique values, but when selecting an option with non-unique value, the wrong selected option is shown...

Still I am closing this issue, because this feature has a low priority in my opinion.

**Closed by basvandenberg** 2017-01-07 12:23 UTC
Labels: improvement
